### ISSUE TITLE
copyright?

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/j4adminui#12]
What is the source of the icons used to create the joomla.woff file

Several of them look very similar to icons that are not free to use

**Comment by kawshar** [comment]
All icons are created for Joomla & Joomla will reserve the right. Well, all svg icons will be available in a separate repo along with the nodejs script to convert font from svg files.

**Comment by brianteeman** [comment]
Really happy to hear that the icons have been created 100% by yourselves and that they have not been copied from non-free sources as obviously this is a very important issues

**Comment by brianteeman** [comment]
Until the evidence that these are 100% original icons is provided and the license for these icons stated this really should stay open

**Comment by kawshar** [comment]
@marcodings please create a repo where we can upload the source files.

Thanks

**Comment by HLeithner** [comment]
beside the images, is there a reason why this is a new repo without history?

**Comment by brianteeman** [comment]
i had hoped that lesson had been learnt so i wasnt going to bead a dead donkey and raise it again

**Comment by kawshar** [comment]
> beside the images, is there a reason why this is a new repo without history?

Actually, it has a long history https://github.com/kawshar/backend-template/tree/newadmin_development

**Comment by brianteeman** [comment]
@kawshar Harald means that this repo has no history. Your fork might as well live on your hard drive and it's not available to this repo. It makes it impossible to see what has changed

**Comment by kawshar** [comment]
@brianteeman I got his question from the first place. But, as the project uploaded directly here, so there is less history. I think a similar thing happened with the previous two designs.

And, I gave him the link so that he can get some ideas that the initiative was not developed behind everyone's back. Since the first day, I have shared the link with all possible networks.

Thanks

**Comment by brianteeman** [comment]
No. The other designs have full history

**Comment by kawshar** [comment]
I see. I think Marco can answer this. All the changes we've made so far have a clear history.  Btw, if we gonna try to merge with Joomla's current build then we will be able to see all changes.

Again, Marco knows better. And, I might not be available for the next 48 hours because I am traveling to the US and it's 35 hours of flight time.

Btw, the icon project will be uploaded by tomorrow in a public Joomla official repo.

Thanks all

**Comment by brianteeman** [comment]
That history needs to be here.

**Comment by kawshar** [comment]
Ok. Got it.

**Comment by marcodings** [comment]
We are looking into the "history" issue which is not trivial. FWIW it will not help with rebasing for a possible merge: George: For the number of commits in j4 rebase isn’t going to be an option.
Aptions are 
- a force push (but we are unsure of the effects)
- start anew based on an import, that would "loose" the issues to date
In both cases commits since start would need to be redone

**Comment by marcodings** [comment]
The icons now live in their own repo https://github.com/joomla-projects/iconfont
Issues about fonts should be discussed there.

As kawshar states "Yes, free to use and custom designed by the team" there should not be any copyright issues. Any further questions on the issue to be discussed there

**Comment by brianteeman** [comment]
There are several ways to maintain the history from the original repo to this one
1. Transfer ownership of the original repo (just a couple of clicks)
2. Fork/clone/mirror his repo (just a couple of clicks)

When/if this template is ready to be merged then the history will also go with it. You can see that from the work on atum. It was merged as a PR from the other repo with https://github.com/joomla/joomla-cms/pull/25570 and if you look at the history of a file in that commit you will see that it has the full history https://github.com/joomla/joomla-cms/commits/4.0-dev/administrator/templates/atum/Service/HTML/Atum.php

### **_I really can not stress enough how important it is to have a full commit history_**

**Comment by marcodings** [comment]
> Aptions are
> 
>     * a force push (but we are unsure of the effects)

An attempt to "push --mirror --force" failed so we had to resort to only force pushing the master branch `git push --force pushsync j4adminui:master`
The repo now has the full history
