### ISSUE TITLE
META alternative template

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/j4adminui#75]
The specification/requirements for this template as stipulated in readme.md state that this is to be an **alternative** template.

If that is still correct then this template repeatedly fails as it has broken the atum template by changing the markup and it gets worse when every time an issue is reported the fix is to make further changes to the core markup and/or code.

We have overrides for a reason and they should be used. The template really shouldnt be changing core code and therefore breaking the existing template.

@marcodings @HLeithner

**Comment by joomlacorner** [comment]
@brianteeman I don't like the atum template that came with J4 alpha.
It doesn't give me any inspirations to keep on using Joomla. Because I think It should give users both interface and robust workable platform at the same time. But for change, the Khonsu template gives Joomla some refresh to the platform. It makes my passion back on using Joomla again. I also think it could inspired many people in the Joomla community. It'll make the J4 much more interesting after Joomla 1.5.  People would like to see major changes after all.

**Comment by Magnytu2** [comment]
Hello Brian, you are a great developer and I thank you for everything you do. But Joomla needs Khonsu to develop our love of Joomla. 
Atum is good, but has a too "developer" approach and does not inspire anything popular. 
I'm not a developer, but just a small user of Joomla! I don't understand your technical problems. But without Khonsu, Joomla will get lost in the dungeons because no one wants to use a CMS that doesn't "whahoo"!
Joomla.org must take a risk and launch a small "doodle" with three questions to ask the community:
Joomla 4 with Atum or Atum + Khonsu?
Choice of administrator template during or after installation?
If we choose Atum + Khonsu, we postpone the launch of J4?
Kawshar needs you to exchange and understand together the technical difficulties. It offers the Joomla community what no template builder has offered you. Please find a common path and make concessions in both directions. For example: keep the same main menu... 
Once again I'm just a Joomla fan.

**Comment by brianteeman** [comment]
It is not a popularity contest. The production department (which I am not part of) defined a set of criteria that must be fulfilled by this template. Currently it is nowhere near that. As I personally feared from before this even started this has not been created as a template ie interchangeable with atum and from today's comments by this team they have no intention of making this anything other than a complete replacement. Despite explicit guidance in that direction it has been completely ignored.

**Comment by marcodings** [comment]
I really want to avoid start spitting hairs about semantics in wording, we are an international community and the command of the English language varies. I would expect that to be understood and considered more.

When production phrased "alternate" it was meant in terms of offering a choice, either people can use "Atum" or they can use "Khonsu". Both templates are required to ensure that all back-end core functionality functions and displays appropriately. It would mean there would be appropriate overrides or "support" in place to ensure they co-exist.
 
An alternate template should be allowed to travel new roads, embrace newer technologies and grow Joomla. If we can not do that we are doing something wrong.
Alternate template does NOT mean that one is sub-ordinate to the other. Atum should function independent of Khosu and vise versa. Production decided that Khonsu would be developed in its own "branch", independently, until criteria are met.
 
We are to worry about the integration at a later date. Any BC breaking consequences are to be submitted as PR's against the main J4 repository. Anything "template related" is just that, related to that specific template. If extensions "play by the rules" there are no consequences to be expected. Consequently an alternative template could be integrated after beta of J4.

There is a lot of work to be done still until we need to cross that "integration" bridge we'll see at that time how to deal with it.

Finally, there is no point at all in discussing incomplete products in general. There is added value in constructive criticism and reporting specific issues for either template.

**Comment by brianteeman** [comment]
> There is a lot of work to be done still until we need to cross that "integration" bridge we'll see at that time how to deal with it.

That's a crazy approach and a real waste of every contributor and testers time. Far better to develop it from day one as an integrated template. Otherwise the people working on this template will end up having to redo the vast majority of the code here so that it will work together with atum - if it is even possible. And if some parts are not possible that will cause further work and distress.

Developing in a separate branch does not preclude ensuring that it is developed from the beginning to work together with atum.

Finally if the development of this template continues as it is then it will lead to a completely avoidable further extensive delay before joomla 4 can be released.

**Comment by brianteeman** [comment]
Keeping closing valid issues because they make you look bad is very childish.

**Comment by uglyeoin** [comment]
I thought he answered you question aptly Brian.  Production are aware of the issue and it seems they have discussed it and have a plan.  Why leave an issue open that is being dealt with?

**Comment by brianteeman** [comment]
Guess there is zero chance of this making the beta release at the end of the month then. A point where the release should be **feature complete**

**Comment by uglyeoin** [comment]
Kind of hard to judge that from where I'm sitting. They seem to be working hard though so I haven't lost hope.
